name: death-to-email
favicon: null
layout_spectrum: 0.05527819041162729
typography_spectrum: 0.7334757891949266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5646075061522424
  lightness: 0.04279715032316744
  saturation: 0.5805099999997765
  rhythmicContrast: 0.5236105446238071
purpose: []
